proc export data=moment.long_top_3 outfile='D:\Dropbox\SAS\Part_2_Yang\Data\Final results.xlsx' dbms=xlsx replace;
sheet='Only long top 3';
run;
%let datadir =D:\Dropbox\SAS\Part_2_Yang;
libname moment "&datadir.\Data";
ods html gpath="&datadir.\graph" path="&datadir.\output" file="momentum.html" ;
ods pdf file="&datadir.\output\momentum.pdf" ;
data moment.raw;
 set moment.raw;
benchmark=(spy-rf)/2;
run;
proc iml;
 reset print;
 *compare with benchmark;
 use moment.raw ;
read all var{benchmark} into bm;*benchmark;
bcm=j(nrow(bm)-6,1);
do i=1 to nrow(bcm);*get the benchmark return from 1999-07;
 bcm[i,1]=bm[i+6,1];
end;
*merge the data from matrices;
use moment.average_a ;
read all var _all_ into a1;
use moment.average_b1 ;
read all var _all_ into b1;
use moment.average_b2 ;
read all var _all_ into b2;
use moment.average_b3 ;
read all var _all_ into b3;
use moment.average_b4 ;
read all var _all_ into b4;
use moment.average_b5 ;
read all var _all_ into b5;
use moment.average_b6 ;
read all var _all_ into b6;
*Correct some numbers of each strategy;
b2[1,1]=.;
b3[1:2,1]=.;
b4[1:3,1]=.;
b5[1:4,1]=.;
b6[1:5,1]=.;
total=a1||b1||b2||b3||b4||b5||b6;
benchmark=j(nrow(a1),1);
do i=1 to nrow(a1);
 benchmark[i,1]=bcm[i,1];
end;
total=benchmark||total;
create moment.total_result from total;
append from total;

*Compare with benchmark;
total_2=total;
do i=1 to nrow(total_2);
 do n=2 to 8;
 total_2[i,n]=total_2[i,n]-total_2[i,1];
 end;
end;
create moment.compare from total_2;
append from total_2;
* Test: if only long top 3;
use moment.output_a;
read all var{col1 col2 col3} into top3; 
ave_top3=j(nrow(top3),1);
do i=1 to nrow(top3);
 ave_top3[i,1]=top3[i,+]/3;
end;
create moment.long_top_3 from ave_top3;
append from ave_top3;
quit;
*Adjust names;
data moment.compare;
  set moment.compare;
  Benchmark=col1;
  A=col2;
  B1=col3;
  B2=col4;
  B3=col5;
  B4=col6;
  B5=col7;
  B6=col8;
drop col1 col2 col3 col4 col5 col6 col7 col8;
run;
data moment.total_result;
  set moment.total_result;
  Benchmark=col1;
  A=col2;
  B1=col3;
  B2=col4;
  B3=col5;
  B4=col6;
  B5=col7;
  B6=col8;
drop col1 col2 col3 col4 col5 col6 col7 col8;
run;
*Compare with benchmark;
proc means data=moment.total_result;*means of each strategy;
var benchmark a b1 b2 b3 b4 b5 b6; 
title "Total results";
proc means data=moment.compare;*each strategy compare with benchmark;
var a b1 b2 b3 b4 b5 b6;
title "Compare with benchmark";
proc means data=moment.long_top_3;*only long top 3;
title "Only long top 3";
run;




*output SAS data as Excel;
proc export data=moment.compare outfile='D:\Dropbox\SAS\Part_2_Yang\Data\Final results.xlsx' dbms=xlsx replace;
sheet='Comapre with benchmark';
proc export data=moment.total_result outfile='D:\Dropbox\SAS\Part_2_Yang\Data\Final results.xlsx' dbms=xlsx replace;
sheet='Total results';
run;
proc export data=moment.long_top_3 outfile='D:\Dropbox\SAS\Part_2_Yang\Data\Final results.xlsx' dbms=xlsx replace;
sheet='Only long top 3';
run;
